version: "3.8"

services:
  back:
    build: ./back
    env_file:
      - ./back/.env_example
      - .env
    restart: always
    ports:
      - "7070:4000"
    volumes:
      - ./logs:/usr/src/app/logs
    command: ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 4000"]
    depends_on:
      - postgres

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "education"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres_education"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "41001:80"
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminminio
    command: server --console-address ":9001" /data


volumes:
  pg-data:
  minio_storage:
