"""update user

Revision ID: 5c8c285fdf50
Revises: fc0372310aca
Create Date: 2024-06-17 13:17:09.962985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8c285fdf50'
down_revision: Union[str, None] = 'fc0372310aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_code_key', 'users', type_='unique')
    op.drop_column('users', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_code_key', 'users', ['code'])
    # ### end Alembic commands ###
