"""update history

Revision ID: c4636b5d361d
Revises: 5c8c285fdf50
Create Date: 2024-06-19 10:05:08.284027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4636b5d361d'
down_revision: Union[str, None] = '5c8c285fdf50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('finish_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'finish_date')
    # ### end Alembic commands ###
